<a href="https://colab.research.google.com/github/Code-With-Hassan/ANN/blob/main/ANN_TESLA_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

import matplotlib.pyplot as plt
plt.style.use('bmh')

In [129]:
#load data
from google.colab import files 
uploaded = files.upload()

Saving TESLA.csv to TESLA (3).csv


In [ ]:
#store the data into data frame 
df = pd.read_csv('TESLA (3).csv')

df = df.iloc[:,1:]
df.shape

In [131]:
#get the numbers of trading days 
df.shape

(10080, 7)

In [ ]:
#visualize the close price data 
plt.figure(figsize=(16,8))
plt.title('Tesla')
plt.xlabel('Days')
plt.ylabel('close price USD ($)')
plt.plot(df["Closing*"])
plt.show()

In [ ]:
# df = df[['Closing*']]
# df.head(6)

In [134]:
#  create a veriable to predict 'X' days out into the future
future_days = 50
#  create a new column (target) shifted 'X' Units/days up
df['prediction'] = df[['Closing*']].shift(-future_days)

In [135]:
#Create the future data set (X) and convert it to a numpy array and remove the last 'x'rows/days
x = np.array(df.drop(['prediction'], 1))[:-future_days]
print(x)


[[1.6574e+02 1.6465e+02 1.6490e+02 ... 2.9020e+05 0.0000e+00 0.0000e+00]
 [1.6474e+02 1.6354e+02 1.6440e+02 ... 2.9540e+05 0.0000e+00 0.0000e+00]
 [1.6531e+02 1.6359e+02 1.6502e+02 ... 2.5610e+05 0.0000e+00 0.0000e+00]
 ...
 [1.9829e+02 1.9547e+02 1.9731e+02 ... 8.7600e+04 0.0000e+00 0.0000e+00]
 [1.9997e+02 1.9600e+02 1.9929e+02 ... 2.1550e+05 0.0000e+00 0.0000e+00]
 [1.9855e+02 1.9431e+02 1.9551e+02 ... 1.8970e+05 0.0000e+00 0.0000e+00]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  


In [136]:
y = np.array(df['prediction'])[:-future_days]
print(y)

[172.26 172.48 168.05 ... 202.2  207.09 208.  ]


In [138]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [139]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)


(8024, 7) (2006, 7)
(8024,) (2006,)


In [141]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#----------------------- Building the model -----------------------#

In [142]:
# Initializing the ANN by calling the Sequential class fromm keras of Tensorflow
ann = tf.keras.models.Sequential()

In [143]:
#----------------------------------------------------------------------------------
# Adding "fully connected" INPUT layer to the Sequential ANN by calling Dense class
#----------------------------------------------------------------------------------
# Number of Units = 6 and Activation Function = Rectifier
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [144]:
#----------------------------------------------------------------------------------
# Adding "fully connected" SECOND layer to the Sequential AMM by calling Dense class
#----------------------------------------------------------------------------------
# Number of Units = 6 and Activation Function = Rectifier
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [145]:
#----------------------------------------------------------------------------------
# Adding "fully connected" OUTPUT layer to the Sequential ANN by calling Dense class
#----------------------------------------------------------------------------------
# Number of Units = 1 and Activation Function = Sigmoid
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [146]:
#----------------------- Training the model -----------------------#
# Compiling the ANN
# Type of Optimizer = Adam Optimizer, Loss Function =  crossentropy for binary dependent variable, and Optimization is done w.r.t. accuracy
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [147]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
251/251 [==============================] - 1s 1ms/step - loss: -196.3857 - accuracy: 0.0000e+00
Epoch 2/100
251/251 [==============================] - 0s 1ms/step - loss: -1941.3613 - accuracy: 0.0000e+00
Epoch 3/100
251/251 [==============================] - 0s 1ms/step - loss: -8566.1514 - accuracy: 0.0000e+00
Epoch 4/100
251/251 [==============================] - 0s 1ms/step - loss: -23246.4258 - accuracy: 0.0000e+00
Epoch 5/100
251/251 [==============================] - 0s 2ms/step - loss: -47884.0273 - accuracy: 0.0000e+00
Epoch 6/100
251/251 [==============================] - 0s 2ms/step - loss: -84053.0938 - accuracy: 0.0000e+00
Epoch 7/100
251/251 [==============================] - 1s 2ms/step - loss: -132840.7031 - accuracy: 0.0000e+00
Epoch 8/100
251/251 [==============================] - 1s 2ms/step - loss: -195263.1094 - accuracy: 0.0000e+00
Epoch 9/100
251/251 [==============================] - 1s 2ms/step - loss: -271944.7500 - accuracy: 0.0000e+00
Epoch 10/10

In [123]:
#print(X_test , "train", X_train)
testDF =  pd.DataFrame(X_test, columns = ['X_test'])
testDF['X_train'] = pd.DataFrame(X_train, columns = ['X_train'])
print(testDF)

ValueError: ignored

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))